/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as DatasetsIndexRouteImport } from './routes/datasets/index'
import { Route as DatasetsAgricultureRouteImport } from './routes/datasets/agriculture'
import { Route as DatasetsClimateRouteImport } from './routes/datasets/climate'
import { Route as DatasetsHealthRouteImport } from './routes/datasets/health'
import { Route as DatasetsLanguageRouteImport } from './routes/datasets/language'
import { Route as GovernanceIndexRouteImport } from './routes/governance/index'
import { Route as GovernanceFundersRouteImport } from './routes/governance/funders'
import { Route as GovernanceSteeringCommitteeRouteImport } from './routes/governance/steering-committee'
import { Route as GovernanceTechnicalAdvisoryPanelsRouteImport } from './routes/governance/technical-advisory-panels'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsIndexRoute = DatasetsIndexRouteImport.update({
  id: '/datasets/',
  path: '/datasets/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsAgricultureRoute = DatasetsAgricultureRouteImport.update({
  id: '/datasets/agriculture',
  path: '/datasets/agriculture',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsClimateRoute = DatasetsClimateRouteImport.update({
  id: '/datasets/climate',
  path: '/datasets/climate',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsHealthRoute = DatasetsHealthRouteImport.update({
  id: '/datasets/health',
  path: '/datasets/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsLanguageRoute = DatasetsLanguageRouteImport.update({
  id: '/datasets/language',
  path: '/datasets/language',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceIndexRoute = GovernanceIndexRouteImport.update({
  id: '/governance/',
  path: '/governance/',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceFundersRoute = GovernanceFundersRouteImport.update({
  id: '/governance/funders',
  path: '/governance/funders',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceSteeringCommitteeRoute =
  GovernanceSteeringCommitteeRouteImport.update({
    id: '/governance/steering-committee',
    path: '/governance/steering-committee',
    getParentRoute: () => rootRouteImport,
  } as any)
const GovernanceTechnicalAdvisoryPanelsRoute =
  GovernanceTechnicalAdvisoryPanelsRouteImport.update({
    id: '/governance/technical-advisory-panels',
    path: '/governance/technical-advisory-panels',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/datasets/agriculture': typeof DatasetsAgricultureRoute
  '/datasets/climate': typeof DatasetsClimateRoute
  '/datasets/health': typeof DatasetsHealthRoute
  '/datasets/language': typeof DatasetsLanguageRoute
  '/governance/funders': typeof GovernanceFundersRoute
  '/governance/steering-committee': typeof GovernanceSteeringCommitteeRoute
  '/governance/technical-advisory-panels': typeof GovernanceTechnicalAdvisoryPanelsRoute
  '/datasets/': typeof DatasetsIndexRoute
  '/governance/': typeof GovernanceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/datasets/agriculture': typeof DatasetsAgricultureRoute
  '/datasets/climate': typeof DatasetsClimateRoute
  '/datasets/health': typeof DatasetsHealthRoute
  '/datasets/language': typeof DatasetsLanguageRoute
  '/governance/funders': typeof GovernanceFundersRoute
  '/governance/steering-committee': typeof GovernanceSteeringCommitteeRoute
  '/governance/technical-advisory-panels': typeof GovernanceTechnicalAdvisoryPanelsRoute
  '/datasets': typeof DatasetsIndexRoute
  '/governance': typeof GovernanceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/datasets/agriculture': typeof DatasetsAgricultureRoute
  '/datasets/climate': typeof DatasetsClimateRoute
  '/datasets/health': typeof DatasetsHealthRoute
  '/datasets/language': typeof DatasetsLanguageRoute
  '/governance/funders': typeof GovernanceFundersRoute
  '/governance/steering-committee': typeof GovernanceSteeringCommitteeRoute
  '/governance/technical-advisory-panels': typeof GovernanceTechnicalAdvisoryPanelsRoute
  '/datasets/': typeof DatasetsIndexRoute
  '/governance/': typeof GovernanceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/apply'
    | '/datasets/agriculture'
    | '/datasets/climate'
    | '/datasets/health'
    | '/datasets/language'
    | '/governance/funders'
    | '/governance/steering-committee'
    | '/governance/technical-advisory-panels'
    | '/datasets/'
    | '/governance/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/apply'
    | '/datasets/agriculture'
    | '/datasets/climate'
    | '/datasets/health'
    | '/datasets/language'
    | '/governance/funders'
    | '/governance/steering-committee'
    | '/governance/technical-advisory-panels'
    | '/datasets'
    | '/governance'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/apply'
    | '/datasets/agriculture'
    | '/datasets/climate'
    | '/datasets/health'
    | '/datasets/language'
    | '/governance/funders'
    | '/governance/steering-committee'
    | '/governance/technical-advisory-panels'
    | '/datasets/'
    | '/governance/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApplyRoute: typeof ApplyRoute
  DatasetsAgricultureRoute: typeof DatasetsAgricultureRoute
  DatasetsClimateRoute: typeof DatasetsClimateRoute
  DatasetsHealthRoute: typeof DatasetsHealthRoute
  DatasetsLanguageRoute: typeof DatasetsLanguageRoute
  GovernanceFundersRoute: typeof GovernanceFundersRoute
  GovernanceSteeringCommitteeRoute: typeof GovernanceSteeringCommitteeRoute
  GovernanceTechnicalAdvisoryPanelsRoute: typeof GovernanceTechnicalAdvisoryPanelsRoute
  DatasetsIndexRoute: typeof DatasetsIndexRoute
  GovernanceIndexRoute: typeof GovernanceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/': {
      id: '/datasets/'
      path: '/datasets'
      fullPath: '/datasets/'
      preLoaderRoute: typeof DatasetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/agriculture': {
      id: '/datasets/agriculture'
      path: '/datasets/agriculture'
      fullPath: '/datasets/agriculture'
      preLoaderRoute: typeof DatasetsAgricultureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/climate': {
      id: '/datasets/climate'
      path: '/datasets/climate'
      fullPath: '/datasets/climate'
      preLoaderRoute: typeof DatasetsClimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/health': {
      id: '/datasets/health'
      path: '/datasets/health'
      fullPath: '/datasets/health'
      preLoaderRoute: typeof DatasetsHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/language': {
      id: '/datasets/language'
      path: '/datasets/language'
      fullPath: '/datasets/language'
      preLoaderRoute: typeof DatasetsLanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance/': {
      id: '/governance/'
      path: '/governance'
      fullPath: '/governance/'
      preLoaderRoute: typeof GovernanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance/funders': {
      id: '/governance/funders'
      path: '/governance/funders'
      fullPath: '/governance/funders'
      preLoaderRoute: typeof GovernanceFundersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance/steering-committee': {
      id: '/governance/steering-committee'
      path: '/governance/steering-committee'
      fullPath: '/governance/steering-committee'
      preLoaderRoute: typeof GovernanceSteeringCommitteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance/technical-advisory-panels': {
      id: '/governance/technical-advisory-panels'
      path: '/governance/technical-advisory-panels'
      fullPath: '/governance/technical-advisory-panels'
      preLoaderRoute: typeof GovernanceTechnicalAdvisoryPanelsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApplyRoute: ApplyRoute,
  DatasetsAgricultureRoute: DatasetsAgricultureRoute,
  DatasetsClimateRoute: DatasetsClimateRoute,
  DatasetsHealthRoute: DatasetsHealthRoute,
  DatasetsLanguageRoute: DatasetsLanguageRoute,
  GovernanceFundersRoute: GovernanceFundersRoute,
  GovernanceSteeringCommitteeRoute: GovernanceSteeringCommitteeRoute,
  GovernanceTechnicalAdvisoryPanelsRoute:
    GovernanceTechnicalAdvisoryPanelsRoute,
  DatasetsIndexRoute: DatasetsIndexRoute,
  GovernanceIndexRoute: GovernanceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
